# Generated by Django 5.1.7 on 2025-03-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gg_lootbox", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="email",
            field=models.EmailField(
                default="sarveshkumar522004@gmail.com", max_length=254
            ),
            preserve_default=False,
        ),
    ]
