# Generated by Django 5.1.7 on 2025-03-31 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gg_lootbox", "0005_productimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productdetail",
            name="images",
        ),
    ]
