# Generated by Django 5.1.7 on 2025-03-31 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gg_lootbox", "0006_remove_productdetail_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.CharField(max_length=500),
        ),
    ]
