# Generated by Django 5.1.7 on 2025-03-31 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gg_lootbox", "0008_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="products/details/"),
        ),
    ]
